name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 9a0210ed-56ec-45aa-baad-7758ab8a7820 # Harusnya di secret, cuman gk ada akses admin
          heroku_app_name: "milestone-selekta"
          heroku_email: "hoaxchecker.sparta20@protonmail.com"
